language: java
dist: trusty
jdk: oraclejdk8
env:
  global:
    - secure: "uJIvjASschndkC56H4XGfykkvnImF85U1ViIiDbipKYizil8TvDqKMLdenKJTrmkiEAE0Ngn0q/718CpJSJ+2vE1rCUtTSyWU1guLdRxT3Y3/7ZWuXuTkdlP3oa53yMqWmUBYD6G2B7bGmTezZ/w4aQUOwDQbxKVkQc2Xi3RxOnbZczfLuVMH6TZWuisgO51SmxhgWu3aRyJE9QKQGafRdQWbcC8DCI8/0Pc6ilIbhzlw3H5lz9f+NJls5/7Dw8B2fi3N3PB/9tmqGa2rOcbD75vNOvzL0KdRdGWbUMWlYMpZQ51Cn9MTV76XOefgrB3iFLYD7EiEnnZSCEeoU0BEnQagMzpFtOwJvPVgiYk+S9FuQbJUM0Z3DETyZf4Cq/DlQKUiSVvowSVPNvl0h8SiyA4QJeUdU29p6zjfSOCeKm7nBvGEuh66U0S/t7ShOUDBkVCRgevHtfHdztuRn49eGSlo6paDf/ozd4EOV9AwsupmmoKjb3RtY412e7vO1mD0cGYxWDS3dqB6B1/LQbyZrR+33qrGKGLketr3A4FDu3iTXOwUam8U9dFjkxYo7PoWuT/9+4IJ8DJQGICmxmqa40ggEQDeNq2RnsxvB7dSVfSr3+Ojvuh3kct991rNxE/7s+6iuBy1Oi379pExO3wiPA9v9eOdV1hza5aV+MS3eQ="
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
      key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    - sourceline: 'deb http://download.mono-project.com/repo/ubuntu trusty main'
      key_url: 'http://download.mono-project.com/repo/xamarin.gpg'
    packages:
    - metacity
    - dotnet-dev-1.0.1
    - mono-complete
#cache:
#  directories:
#  - "$HOME/apache-maven-3.5.0"
#before_install:
#- export M2_HOME=$HOME/apache-maven-3.5.0
#- if [ ! -d $M2_HOME/bin ]; then curl https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz | tar zxf - -C $HOME; fi
#- export PATH=$M2_HOME/bin:$PATH
before_install:
  - nvm install 7
  - node --version
  - dotnet --version
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - true
script:
  - if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]] ; then
       mvn clean install;
    else
       mvn clean verify;
    fi
after_success:
  - if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]] ; then
     cd repository/;
     mvn deploy;
    fi
